"""Early-warning bulletin: alert level per town, in English and Hindi, plus CAP 1.2.

Alert levels
------------
The CWC *Guidelines for Developing Emergency Action Plans for Dams* (2016)
require inundation maps with arrival times for every downstream settlement;
it is the district's Emergency Action Plan that sets the trigger thresholds.
Until a district supplies its own, FloodGuard applies the convention below,
which is printed on every bulletin so nobody mistakes it for a statutory
threshold:

| Level | Condition at the town |
| --- | --- |
| RED — evacuate now | wave arrives within 120 min AND (AIDR hazard >= H4 OR depth >= 1.2 m) |
| ORANGE — prepare to evacuate | flooded AND (hazard >= H3 OR depth >= 0.5 m) |
| YELLOW — alert | flooded above the wet threshold, shallower and slower than the above |
| NONE | inside the domain and never flooded |
| NOT ASSESSED | outside the simulation domain — the model says nothing |

Hazard classes: AIDR Handbook 7 (2017) Table 6.1, as used on the map.

The CAP alert
-------------
India's national alert dissemination (NDMA's SACHET platform) is built on the
OASIS Common Alerting Protocol 1.2. FloodGuard writes a CAP 1.2 document so a
scenario can be loaded into such a system for an exercise. It will only emit
`status` Exercise, Test or Draft — never Actual. A model scenario is not an
observed event, so `certainty` is always "Possible", and the sender name says
"model output". Issuing a real warning is an authority's decision, not a
tool's.
"""

from __future__ import annotations

import time
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from typing import Any

import numpy as np

RED_ARRIVAL_MIN = 120.0
RED_DEPTH_M = 1.2
ORANGE_DEPTH_M = 0.5

LEVELS = ("RED", "ORANGE", "YELLOW", "NONE", "NOT_ASSESSED")

LEVEL_TEXT = {
    "RED": ("Evacuate now", "लाल — तुरंत सुरक्षित ऊँचे स्थान पर जाएँ"),
    "ORANGE": ("Prepare to evacuate", "नारंगी — निकासी की तैयारी करें"),
    "YELLOW": ("Alert — stay informed", "पीला — सतर्क रहें"),
    "NONE": ("No flooding in this scenario", "इस परिदृश्य में बाढ़ नहीं"),
    "NOT_ASSESSED": ("Not assessed — outside the model", "आकलन नहीं — मॉडल क्षेत्र से बाहर"),
}

DIRECTION_HI = {
    "N": "उत्तर", "NE": "उत्तर-पूर्व", "E": "पूर्व", "SE": "दक्षिण-पूर्व",
    "S": "दक्षिण", "SW": "दक्षिण-पश्चिम", "W": "पश्चिम", "NW": "उत्तर-पश्चिम",
}

CONVENTION = (
    f"Alert levels are a FloodGuard convention pending the district Emergency Action "
    f"Plan: RED if the wave arrives within {RED_ARRIVAL_MIN:.0f} min and the AIDR hazard "
    f"is H4 or worse or depth is {RED_DEPTH_M} m or more; ORANGE if hazard is H3 or worse "
    f"or depth is {ORANGE_DEPTH_M} m or more; YELLOW if flooded at all."
)

DISCLAIMER_EN = (
    "MODEL SCENARIO — NOT AN OFFICIAL WARNING. Generated by FloodGuard India from a "
    "hypothetical dam-break simulation. Times and depths carry the uncertainties stated "
    "in the run report, dominated by breach geometry."
)
DISCLAIMER_HI = (
    "यह मॉडल-आधारित अभ्यास संदेश है, आधिकारिक चेतावनी नहीं। समय और गहराई अनुमानित हैं।"
)


@dataclass
class TownAlert:
    name: str
    lon: float
    lat: float
    level: str
    arrival_min: float | None
    max_depth_m: float | None
    max_velocity_ms: float | None
    hazard_class: str | None
    population: int | None
    safe_ground: dict[str, Any] | None = None
    safe_ground_reason: str = ""
    reasons: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "lon": self.lon,
            "lat": self.lat,
            "level": self.level,
            "action_en": LEVEL_TEXT[self.level][0],
            "action_hi": LEVEL_TEXT[self.level][1],
            "arrival_min": self.arrival_min,
            "max_depth_m": self.max_depth_m,
            "max_velocity_ms": self.max_velocity_ms,
            "hazard_class": self.hazard_class,
            "population": self.population,
            "safe_ground": self.safe_ground,
            "safe_ground_reason": self.safe_ground_reason,
            "reasons": self.reasons,
        }


def hazard_label(depth: float | None, velocity: float | None) -> str | None:
    if depth is None or velocity is None:
        return None
    from floodguard.postprocess.hazard import HAZARD_CLASSES, classify

    code = int(classify(np.array([[depth]]), np.array([[velocity]]))[0, 0])
    if code == 0:
        return None
    return next(h.label for h in HAZARD_CLASSES if h.code == code)


def classify_town(town: dict[str, Any], wet_threshold_m: float = 0.3) -> TownAlert:
    """Alert level for one row of the run's town table."""
    depth = town.get("max_depth_m")
    velocity = town.get("max_velocity_ms")
    arrival = town.get("arrival_min")
    hz = hazard_label(depth, velocity)
    hz_rank = int(hz[1]) if hz else 0
    reasons: list[str] = []

    if not town.get("in_domain", True):
        level = "NOT_ASSESSED"
        reasons.append("outside the simulation domain")
    elif depth is None or depth < wet_threshold_m or arrival is None:
        level = "NONE"
    elif arrival <= RED_ARRIVAL_MIN and (hz_rank >= 4 or depth >= RED_DEPTH_M):
        level = "RED"
        reasons.append(f"arrives in {arrival:.0f} min")
        reasons.append(f"hazard {hz}" if hz_rank >= 4 else f"depth {depth:.1f} m")
    elif hz_rank >= 3 or depth >= ORANGE_DEPTH_M:
        level = "ORANGE"
        reasons.append(f"hazard {hz}, depth {depth:.1f} m")
    else:
        level = "YELLOW"
        reasons.append(f"shallow flooding, {depth:.2f} m")

    return TownAlert(
        name=town["name"],
        lon=town["lon"],
        lat=town["lat"],
        level=level,
        arrival_min=arrival,
        max_depth_m=depth,
        max_velocity_ms=velocity,
        hazard_class=hz,
        population=town.get("population"),
        reasons=reasons,
    )


def build(
    run: dict[str, Any],
    *,
    scenario_name: str,
    depth: np.ndarray | None = None,
    bed: np.ndarray | None = None,
    transform=None,
    crs: str | None = None,
    wet_threshold_m: float = 0.3,
    freeboard_m: float = 2.0,
) -> dict[str, Any]:
    """The complete bulletin payload for one run."""
    alerts = [classify_town(t, wet_threshold_m) for t in run.get("towns", [])]

    safe_note = ""
    if depth is not None and bed is not None and transform is not None and crs:
        from floodguard.warning.safe_ground import nearest_safe_ground

        found = nearest_safe_ground(
            depth, bed, transform, crs, [(a.lon, a.lat) for a in alerts],
            wet_threshold_m=wet_threshold_m, freeboard_m=freeboard_m,
        )
        for alert, (sg, reason) in zip(alerts, found):
            if alert.level in ("RED", "ORANGE", "YELLOW"):
                alert.safe_ground = sg.to_dict() if sg else None
                alert.safe_ground_reason = reason
    else:
        safe_note = "Safe ground was not computed: the run has no bed raster."
        for alert in alerts:
            if alert.level in ("RED", "ORANGE", "YELLOW"):
                alert.safe_ground_reason = safe_note

    order = {lvl: i for i, lvl in enumerate(LEVELS)}
    alerts.sort(key=lambda a: (order[a.level], a.arrival_min if a.arrival_min is not None else 1e9))

    counts = {lvl: sum(a.level == lvl for a in alerts) for lvl in LEVELS}
    at_risk_pop = [a.population for a in alerts if a.level in ("RED", "ORANGE")]
    issued = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    payload = {
        "run_id": run.get("run_id"),
        "scenario": scenario_name,
        "issued_utc": issued,
        "towns": [a.to_dict() for a in alerts],
        "counts": counts,
        # Census population of towns at RED/ORANGE; null if any is unknown,
        # never a partial sum passed off as a total.
        "population_red_orange": (
            sum(at_risk_pop) if at_risk_pop and all(p is not None for p in at_risk_pop)
            else None
        ),
        "convention": CONVENTION,
        "safe_ground_method": (
            f"Nearest cell that never flooded and stands at least {freeboard_m:.0f} m above "
            f"the computed flood surface nearby. Straight-line distance, not a route; "
            f"limited to the modelled corridor."
        ),
        "disclaimer_en": DISCLAIMER_EN,
        "disclaimer_hi": DISCLAIMER_HI,
        "note": safe_note,
    }
    payload["text_en"] = render_text(payload, "en")
    payload["text_hi"] = render_text(payload, "hi")
    payload["sms"] = [sms(a, "en") for a in alerts if a.level in ("RED", "ORANGE", "YELLOW")]
    payload["sms_hi"] = [sms(a, "hi") for a in alerts if a.level in ("RED", "ORANGE", "YELLOW")]
    return payload


# --- text renderings ---------------------------------------------------------------


def _fmt_minutes(m: float | None) -> str:
    if m is None:
        return "—"
    if m < 90:
        return f"{m:.0f} min"
    return f"{int(m // 60)} h {int(round(m % 60)):02d} min"


def _fmt_minutes_hi(m: float | None) -> str:
    if m is None:
        return "—"
    if m < 90:
        return f"{m:.0f} मिनट"
    return f"{int(m // 60)} घंटे {int(round(m % 60)):02d} मिनट"


def render_text(payload: dict[str, Any], lang: str) -> str:
    lines: list[str] = []
    if lang == "hi":
        lines += [
            "बाँध टूटने से बाढ़ — चेतावनी बुलेटिन (अभ्यास)",
            f"परिदृश्य: {payload['scenario']}",
            f"जारी (UTC): {payload['issued_utc']}",
            "",
        ]
        for t in payload["towns"]:
            lines.append(f"■ {t['name']}: {t['action_hi']}")
            if t["arrival_min"] is not None and t["level"] in ("RED", "ORANGE", "YELLOW"):
                lines.append(
                    f"   बाढ़ का पानी लगभग {_fmt_minutes_hi(t['arrival_min'])} "
                    f"में पहुँच सकता है; अधिकतम गहराई लगभग {t['max_depth_m']:.1f} मीटर।"
                )
            sg = t.get("safe_ground")
            if sg:
                lines.append(
                    f"   निकटतम सुरक्षित ऊँची भूमि: {DIRECTION_HI[sg['direction']]} दिशा में "
                    f"लगभग {sg['distance_km']:.1f} किमी (सीधी दूरी)।"
                )
        lines += ["", payload["disclaimer_hi"], "(स्थानों के नाम अंग्रेज़ी में दिए गए हैं।)"]
        return "\n".join(lines)

    lines += [
        "DAM-BREAK FLOOD — WARNING BULLETIN (EXERCISE)",
        f"Scenario : {payload['scenario']}",
        f"Issued   : {payload['issued_utc']} UTC",
        f"Run      : {payload['run_id']}",
        "",
        f"RED {payload['counts']['RED']} · ORANGE {payload['counts']['ORANGE']} · "
        f"YELLOW {payload['counts']['YELLOW']} · no flooding {payload['counts']['NONE']} · "
        f"not assessed {payload['counts']['NOT_ASSESSED']}",
        "",
    ]
    for t in payload["towns"]:
        lines.append(f"[{t['level']}] {t['name']} — {t['action_en']}")
        if t["level"] in ("RED", "ORANGE", "YELLOW"):
            lines.append(
                f"    arrival {_fmt_minutes(t['arrival_min'])}, max depth "
                f"{t['max_depth_m']:.1f} m, max velocity {t['max_velocity_ms']:.1f} m/s, "
                f"hazard {t['hazard_class'] or '—'}"
            )
            sg = t.get("safe_ground")
            if sg:
                lines.append(
                    f"    nearest safe ground: {sg['distance_km']:.1f} km {sg['direction']} "
                    f"(straight line), {sg['height_above_flood_m']:.0f} m above the flood"
                )
            elif t.get("safe_ground_reason"):
                lines.append(f"    nearest safe ground: — ({t['safe_ground_reason']})")
    lines += [
        "",
        payload["convention"],
        payload["safe_ground_method"],
        "",
        payload["disclaimer_en"],
    ]
    return "\n".join(lines)


def sms(alert: TownAlert, lang: str = "en") -> dict[str, Any]:
    """One SMS per town, with its length and GSM/UCS-2 segment count."""
    arrival = _fmt_minutes(alert.arrival_min)
    sg = alert.safe_ground
    if lang == "hi":
        text = (
            f"अभ्यास: {alert.name} — {LEVEL_TEXT[alert.level][1]}। पानी ~{_fmt_minutes_hi(alert.arrival_min)}"
            f" में, गहराई ~{alert.max_depth_m:.0f} मी।"
            + (f" सुरक्षित स्थान {DIRECTION_HI[sg['direction']]} {sg['distance_km']:.1f} किमी।" if sg else "")
        )
        per_segment = 70  # UCS-2
    else:
        text = (
            f"EXERCISE {alert.level}: {alert.name} - {LEVEL_TEXT[alert.level][0]}. "
            f"Flood in ~{arrival}, depth ~{alert.max_depth_m:.0f} m."
            + (f" Safe ground {sg['distance_km']:.1f} km {sg['direction']}." if sg else "")
        )
        per_segment = 160  # GSM-7
    return {
        "town": alert.name,
        "level": alert.level,
        "text": text,
        "chars": len(text),
        "segments": max(1, -(-len(text) // per_segment)),
    }


# --- CAP 1.2 --------------------------------------------------------------------------

CAP_NS = "urn:oasis:names:tc:emergency:cap:1.2"
ALLOWED_STATUS = ("Exercise", "Test", "Draft")
_CAP_MAP = {
    "RED": ("Evacuate", "Immediate", "Extreme"),
    "ORANGE": ("Prepare", "Expected", "Severe"),
    "YELLOW": ("Monitor", "Expected", "Moderate"),
}


def cap_xml(
    payload: dict[str, Any],
    *,
    status: str = "Exercise",
    sender: str = "floodguard@localhost",
    radius_km: float = 3.0,
) -> str:
    """A CAP 1.2 alert with one <info> per alert level and language.

    Refuses status "Actual": see the module docstring.
    """
    if status not in ALLOWED_STATUS:
        raise ValueError(
            f"CAP status {status!r} refused. FloodGuard emits only {ALLOWED_STATUS}; an "
            f"Actual alert must be issued by the competent authority."
        )
    ET.register_namespace("", CAP_NS)

    def el(parent, tag, text=None):
        node = ET.SubElement(parent, f"{{{CAP_NS}}}{tag}")
        if text is not None:
            node.text = str(text)
        return node

    sent = payload["issued_utc"].replace("Z", "+00:00")
    alert = ET.Element(f"{{{CAP_NS}}}alert")
    el(alert, "identifier", f"floodguard-{payload['run_id']}-{int(time.time())}")
    el(alert, "sender", sender)
    el(alert, "sent", sent)
    el(alert, "status", status)
    el(alert, "msgType", "Alert")
    el(alert, "scope", "Public")
    el(alert, "note", DISCLAIMER_EN + " " + CONVENTION)

    for level in ("RED", "ORANGE", "YELLOW"):
        towns = [t for t in payload["towns"] if t["level"] == level]
        if not towns:
            continue
        response, urgency, severity = _CAP_MAP[level]
        for lang, action_idx, headline in (
            ("en-IN", 0, f"Dam-break flood ({level}): {payload['scenario']}"),
            ("hi-IN", 1, f"बाँध टूटने से बाढ़ ({level})"),
        ):
            info = el(alert, "info")
            el(info, "language", lang)
            el(info, "category", "Geo")
            el(info, "category", "Infra")
            el(info, "event", "Dam break flood" if lang == "en-IN" else "बाँध टूटने से बाढ़")
            el(info, "responseType", response)
            el(info, "urgency", urgency)
            el(info, "severity", severity)
            # A modelled scenario, not an observation.
            el(info, "certainty", "Possible")
            el(info, "senderName", "FloodGuard India (model output)")
            el(info, "headline", headline)
            text = payload["text_en"] if lang == "en-IN" else payload["text_hi"]
            el(info, "description", text)
            el(info, "instruction", LEVEL_TEXT[level][action_idx])
            first = min((t["arrival_min"] for t in towns if t["arrival_min"] is not None), default=None)
            if first is not None:
                param = el(info, "parameter")
                el(param, "valueName", "earliestArrivalMinutes")
                el(param, "value", f"{first:.0f}")
            for t in towns:
                area = el(info, "area")
                el(area, "areaDesc", t["name"])
                el(area, "circle", f"{t['lat']:.5f},{t['lon']:.5f} {radius_km:.1f}")

    ET.indent(alert)
    return '<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(alert, encoding="unicode")
